loginDjango/loginDjango/loginDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('userprofiles.urls', namespace='userprofiles'),)
]

loginDjango/loginDjango/userprofiles/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
            url(r'^login/$', views.authentication, name='authentication'),
            url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
            url(r'^$', views.hello, name="hello"),
]

loginDjango/loginDjango/userprofiles/models.py
from django.db import models

# Create your models here.

loginDjango/loginDjango/userprofiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

def authentication(request):
    if request.method == 'POST':
        action = request.POST.get('action', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        if action == 'signup':
            user = User.objects.create_user(username=username,
                    password=password)
            user.save()
        elif action == 'login':
            user = authenticate(username=username, password=
                password)
            login(request, user)
            return redirect('/')

            return render(request, 'login.html', {})

def hello(request):
        return render(request, 'hello.html', {})

loginDjango/loginDjango/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login Django</title>
  </head>
  <body>
      {% block login_content %}
      {% endblock %}
      {% block content %}
      {% endblock %}
  </body>
</html>

loginDjango/loginDjango/templates/hello.html
{% extends "base.html" %}

{% block content %}
  <h1>Hello</h1>

  <a href="{% url "userprofiles:logout" %}">logout</a>


  <h2>
    {% if user.is_authenticated %}
      {{ user.username }}
    {% else %}
      <a href="{% url "userprofile:login" %}"></a>
    {% endif %}

  </h2>
{% endblock %}

loginDjango/loginDjango/templates/login.html
{% extends "base.html" %}

{% block login_content %}
      <h1>Login</h1>
      <form action="" method="post">
          {% crsf_token %}
          <input type="hidden" name="action" value="login">

          <input type="text" name="username">
          <input type="text" name="password">

          <button type="submit" name="button">Login</button>

      </form>
      <h1>SignUp</h1>
      <form action="index.html" method="post">
        {% crsf_toke %}
        <input type="hidden" name="action" value="signup">

        <input type="text" name="username" value="">
        <input type="text" name="password" value="">

        <button type="submit" name="button">Signup</button>
      </form>
{% endblock %}